In [1]:
#NumPY

import numpy as np
l=[1,2,3,4]
l

[1, 2, 3, 4]

In [2]:
a=np.array(l)
print(a)

[1 2 3 4]


In [3]:
type(a)

numpy.ndarray

In [4]:
a.shape

(4,)

In [5]:
l1=[1,2,3,4]
l2=[5,6,7,8]
l3=[9,10,11,12]
a=np.array([l1,l2,l3])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
a.shape

(3, 4)

In [7]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
a[1:3,:2]

array([[ 5,  6],
       [ 9, 10]])

In [10]:
a[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [11]:
a[1:2,1:3]

array([[6, 7]])

In [12]:
b=np.arange(1,11)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
b=np.arange(1,11,step=3)
b

array([ 1,  4,  7, 10])

In [14]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [15]:
c=np.arange(1,11)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
c[5:]=20
c

array([ 1,  2,  3,  4,  5, 20, 20, 20, 20, 20])

In [17]:
c<3

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [18]:
c*10

array([ 10,  20,  30,  40,  50, 200, 200, 200, 200, 200])

In [19]:
c[c<3]

array([1, 2])

In [20]:
np.arange(100,110).reshape(2,5)

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109]])

In [21]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [22]:
np.random.rand(4,5)

array([[0.92613876, 0.36024971, 0.15715133, 0.21384819, 0.23031184],
       [0.90438719, 0.7168325 , 0.96896191, 0.44953148, 0.37199762],
       [0.34052979, 0.15958492, 0.75274788, 0.42607636, 0.2035687 ],
       [0.70551635, 0.56122118, 0.89667777, 0.4731807 , 0.81190099]])