In [ ]:
import torch

In [ ]:
print("this is the best laptop")

this is the best laptop


In [ ]:
x=torch.empty(2,2,3)
print(x)

tensor([[[7.1428e+31, 2.0196e-19, 1.1723e-19],
         [5.0746e+31, 4.2964e+24, 4.6304e+27]],

        [[6.9776e+22, 7.5244e+28, 1.8524e+28],
         [1.7836e+31, 6.8608e+22, 1.2119e+25]]])


In [ ]:
x=torch.rand(2,3)
x

tensor([[0.2771, 0.8573, 0.9915],
        [0.8611, 0.0884, 0.1540]])

In [ ]:
x=torch.zeros(2,4)
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
x=torch.ones(1)
x

tensor([1.])

In [ ]:
x=torch.ones(1,4,dtype=torch.int)
x

tensor([[1, 1, 1, 1]], dtype=torch.int32)

In [ ]:
x.size()

torch.Size([1, 4])

In [ ]:
x=torch.tensor([2.5,0.1])
x

tensor([2.5000, 0.1000])

In [ ]:
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)
x+y

tensor([[0.5065, 0.6852],
        [0.9181, 0.8023]])
tensor([[0.3967, 0.9210],
        [0.5518, 0.3833]])


tensor([[0.9032, 1.6062],
        [1.4699, 1.1856]])

In [ ]:
x-y

tensor([[ 0.1098, -0.2358],
        [ 0.3663,  0.4190]])

In [ ]:
x*y

tensor([[0.2009, 0.6310],
        [0.5066, 0.3075]])

In [ ]:
x=torch.rand(5,3)
x

tensor([[0.9319, 0.9072, 0.0429],
        [0.6854, 0.6079, 0.5979],
        [0.4646, 0.2489, 0.9408],
        [0.5083, 0.1917, 0.2862],
        [0.8730, 0.1290, 0.8502]])

In [ ]:
x[:,0]

tensor([0.9319, 0.6854, 0.4646, 0.5083, 0.8730])

In [ ]:
x[1,1]

tensor(0.6079)

In [ ]:
x.size()

torch.Size([5, 3])

In [ ]:
z=x.view(-1,5)
z

tensor([[0.9319, 0.9072, 0.0429, 0.6854, 0.6079],
        [0.5979, 0.4646, 0.2489, 0.9408, 0.5083],
        [0.1917, 0.2862, 0.8730, 0.1290, 0.8502]])

In [ ]:
z.size()

torch.Size([3, 5])

In [ ]:
x.dtype

torch.float32